# ************************************* CHECKMARX CONFIGURATION FILE **********************************************
# * To use this file as 'Config as code' you need to save it under a specific location in your source directory:  *
# * Under your root, create a folder: ".checkmarx"                                                                *
# * In this new folder place this file, and rename it to: "config.yml"                                            *
# *****************************************************************************************************************

version: 1

# checkmarx-specific related configuration
# every value in this section is optional 
checkmarx: 
  # configure the checkmarx scan parameters for scanning this specific project
  scan:
    # configure the checkmarx scan configurations for scanning this specific project
    configs:
      # configure the SAST related configurations this specific project
      sast:
        # configure the SAST preset name used for this specific project
        presetName: 'High and Medium'
         # configure if this specific project will be run incrementally or will it run a full scan 
        incremental: 'false'
        languageMode: 'multi'
        filter: '!*.java,!*.cpp, !**/*test*/**, !**/*.Tests/**'
        engineVerbose: 'true'
      sca:
        filter: '!*.cpp, !**/*test*/**, !**/*.Tests/**'
        exploitablePath: 'true'
        lastSastScanTime: '10'
      kics:
        # configure the KICS scan to filter files by platform-specific extensions.
        filter: '!*.tf'
        # configure the KICS scan to use only queries from the specified platforms.
        platforms: 'Ansible,CloudFormation,Dockerfile'
        # the presetId for KICS accepts only a single preset ID (must be a valid UUID).
        presetId: ''
